/*
 * Copyright (C) 2026 SPORT-SERVICE RS★R
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

export const HERO13_EASY_SUPER_PHOTO_PRESET = 786432;
export const HERO13_EASY_NIGHT_PHOTO_PRESET = 786433;
export const HERO13_EASY_BURST_PHOTO_PRESET = 786434;

export const HERO13_EASY_TIMEWARP_PRESET = 851968;
export const HERO13_EASY_STAR_TRAILS_PRESET = 851969;
export const HERO13_EASY_LIGHT_PAINTING_PRESET = 851970;
export const HERO13_EASY_VEHICLE_LIGHTS_PRESET = 851971;

export const HERO13_MAX_TIMEWARP_2_PRESET = 1114112;
export const HERO13_MAX_STAR_TRAILS_2_PRESET = 1114113;
export const HERO13_MAX_LIGHT_PAINTING_2_PRESET = 1114114;
export const HERO13_MAX_VEHICLE_LIGHTS_2_PRESET = 1114115;

export const HERO13_EASY_MAX_VIDEO_PRESET = 1441792;
export const HERO13_EASY_MAX_PHOTO_PRESET = 1507328;
export const HERO13_EASY_MAX_TIMEWARP_PRESET = 1572864;
export const HERO13_EASY_MAX_STAR_TRAILS_PRESET = 1572865;
export const HERO13_EASY_MAX_LIGHT_PAINTING_PRESET = 1572866;
export const HERO13_EASY_MAX_VEHICLE_LIGHTS_PRESET = 1572867;

export const HERO13_MACRO_TIMELAPSE_PRESET = 2490368;
export const HERO13_MACRO_NIGHTLAPSE_PRESET = 2490369;

export const HERO13_EASY_MACRO_PHOTO_PRESET = 2621440;
export const HERO13_EASY_MACRO_NIGHT_PHOTO_PRESET = 2621441;
export const HERO13_EASY_MACRO_TIMELAPSE_PRESET = 2686976;
export const HERO13_EASY_MACRO_NIGHTLAPSE_PRESET = 2686977;

export const HERO13_ANAMORPHIC_SUPER_PHOTO_PRESET = 2949120;
export const HERO13_ANAMORPHIC_NIGHT_PHOTO_PRESET = 2949123;

export const HERO13_EASY_ANAMORPHIC_SUPER_PHOTO_PRESET = 3145728;
export const HERO13_EASY_ANAMORPHIC_NIGHT_PHOTO_PRESET = 3145729;
export const HERO13_EASY_ANAMORPHIC_TIMEWARP_PRESET = 3211264;

export const EASY_ANAMORPHIC_SUPER_PHOTO_PRESET_HERO13 = HERO13_EASY_ANAMORPHIC_SUPER_PHOTO_PRESET;
export const EASY_ANAMORPHIC_NIGHT_PHOTO_PRESET_HERO13 = HERO13_EASY_ANAMORPHIC_NIGHT_PHOTO_PRESET;
export const EASY_ANAMORPHIC_TIMEWARP_PRESET_HERO13 = HERO13_EASY_ANAMORPHIC_TIMEWARP_PRESET;
export const EASY_MACRO_PHOTO_PRESET_HERO13 = HERO13_EASY_MACRO_PHOTO_PRESET;
export const EASY_MACRO_NIGHT_PHOTO_PRESET_HERO13 = HERO13_EASY_MACRO_NIGHT_PHOTO_PRESET;
export const EASY_MACRO_TIMELAPSE_PRESET_HERO13 = HERO13_EASY_MACRO_TIMELAPSE_PRESET;
export const EASY_MACRO_NIGHTLAPSE_PRESET_HERO13 = HERO13_EASY_MACRO_NIGHTLAPSE_PRESET;

export const HERO13_EASY_PHOTO_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_EASY_SUPER_PHOTO_PRESET,
  HERO13_EASY_NIGHT_PHOTO_PRESET,
  HERO13_EASY_BURST_PHOTO_PRESET,
  HERO13_EASY_MAX_PHOTO_PRESET,
  HERO13_EASY_ANAMORPHIC_SUPER_PHOTO_PRESET,
  HERO13_EASY_ANAMORPHIC_NIGHT_PHOTO_PRESET,
  HERO13_EASY_MACRO_PHOTO_PRESET,
  HERO13_EASY_MACRO_NIGHT_PHOTO_PRESET,
]);

export const HERO13_EASY_MAX_TRAIL_2_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_EASY_MAX_STAR_TRAILS_PRESET,
  HERO13_EASY_MAX_LIGHT_PAINTING_PRESET,
  HERO13_EASY_MAX_VEHICLE_LIGHTS_PRESET,
]);

export const HERO13_EASY_TRAIL_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_EASY_STAR_TRAILS_PRESET,
  HERO13_EASY_LIGHT_PAINTING_PRESET,
  HERO13_EASY_VEHICLE_LIGHTS_PRESET,
  HERO13_EASY_MAX_STAR_TRAILS_PRESET,
  HERO13_EASY_MAX_LIGHT_PAINTING_PRESET,
  HERO13_EASY_MAX_VEHICLE_LIGHTS_PRESET,
]);

export const HERO13_MAX_TRAIL_2_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_MAX_STAR_TRAILS_2_PRESET,
  HERO13_MAX_LIGHT_PAINTING_2_PRESET,
  HERO13_MAX_VEHICLE_LIGHTS_2_PRESET,
  HERO13_EASY_MAX_STAR_TRAILS_PRESET,
  HERO13_EASY_MAX_LIGHT_PAINTING_PRESET,
  HERO13_EASY_MAX_VEHICLE_LIGHTS_PRESET,
]);

export const HERO13_EASY_TIMELAPSE_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_EASY_TIMEWARP_PRESET,
  HERO13_EASY_MAX_TIMEWARP_PRESET,
  HERO13_EASY_ANAMORPHIC_TIMEWARP_PRESET,
  HERO13_EASY_STAR_TRAILS_PRESET,
  HERO13_EASY_LIGHT_PAINTING_PRESET,
  HERO13_EASY_VEHICLE_LIGHTS_PRESET,
  HERO13_EASY_MAX_STAR_TRAILS_PRESET,
  HERO13_EASY_MAX_LIGHT_PAINTING_PRESET,
  HERO13_EASY_MAX_VEHICLE_LIGHTS_PRESET,
  HERO13_EASY_MACRO_TIMELAPSE_PRESET,
]);

export const HERO13_MACRO_LAPSE_PRESET_IDS: ReadonlySet<number> = new Set([
  HERO13_MACRO_TIMELAPSE_PRESET,
  HERO13_MACRO_NIGHTLAPSE_PRESET,
  HERO13_EASY_MACRO_TIMELAPSE_PRESET,
  HERO13_EASY_MACRO_NIGHTLAPSE_PRESET,
]);
