/*
 * Copyright (C) 2026 SPORT-SERVICE RS★R
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Expo Config Plugin: with-release-signing
 *
 * When android/app/build.gradle is regenerated by `npx expo prebuild`,
 * this plugin automatically inserts code so that the release build type
 * loads release signing credentials from environment variables, falling back
 * to `android/keystore.properties`, and signs using the release keystore.
 *
 * keystore.properties is ignored by git. In environments where this file does
 * not exist (like CI), provide app-specific RSR_REMOTE_* environment
 * variables or it falls back to debug signing as usual.
 *
 * Usage: Add `"./plugins/withReleaseSigning"` to `expo.plugins` in app.json.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const KEYSTORE_LOADER = `
// --- withReleaseSigning: load release keystore credentials ---
// keystore.properties lives under build-config/android/ at the Expo project
// root so it survives \`npx expo prebuild --clean\` (which regenerates android/).
// Environment variables take precedence so CI can build without this file.
// See build-config/android/README.md for setup.
def keystorePropertiesFile = rootProject.file("../build-config/android/keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
def releaseStoreFile = System.getenv("RSR_REMOTE_RELEASE_STORE_FILE") ?: keystoreProperties['RELEASE_STORE_FILE']
def releaseStorePassword = System.getenv("RSR_REMOTE_RELEASE_STORE_PASSWORD") ?: keystoreProperties['RELEASE_STORE_PASSWORD']
def releaseKeyAlias = System.getenv("RSR_REMOTE_RELEASE_KEY_ALIAS") ?: keystoreProperties['RELEASE_KEY_ALIAS']
def releaseKeyPassword = System.getenv("RSR_REMOTE_RELEASE_KEY_PASSWORD") ?: keystoreProperties['RELEASE_KEY_PASSWORD']
// --- end withReleaseSigning ---
`;

const RELEASE_SIGNING_CONFIG = `        if (releaseStoreFile) {
            release {
        storeFile file(releaseStoreFile)
        storePassword releaseStorePassword
        keyAlias releaseKeyAlias
        keyPassword releaseKeyPassword
            }
        }
`;

const RELEASE_SIGNING_CONFIG_USAGE = `            signingConfig releaseStoreFile ? signingConfigs.findByName("release") : signingConfigs.debug`;

function injectKeystoreLoader(contents) {
  if (contents.includes('withReleaseSigning')) return contents;
  // Insert keystore loader just before the `android {` block.
  const anchor = /\nandroid\s*\{/;
  if (!anchor.test(contents)) {
    throw new Error('[withReleaseSigning] Could not locate `android {` block in build.gradle');
  }
  return contents.replace(anchor, `${KEYSTORE_LOADER}\nandroid {`);
}

function injectReleaseSigningConfig(contents) {
  if (contents.includes('storeFile file(releaseStoreFile)')) return contents;
  // Insert release signingConfig inside signingConfigs { ... } block, after the debug block.
  const debugBlockRegex = /(signingConfigs\s*\{[\s\S]*?debug\s*\{[\s\S]*?\}\s*)(\n\s*\})/;
  if (!debugBlockRegex.test(contents)) {
    const fallbackRegex = /(signingConfigs\s*\{)/;
    if (fallbackRegex.test(contents)) {
      return contents.replace(fallbackRegex, `$1\n${RELEASE_SIGNING_CONFIG}`);
    }
    throw new Error('[withReleaseSigning] Could not locate signingConfigs block');
  }
  return contents.replace(debugBlockRegex, `$1\n${RELEASE_SIGNING_CONFIG}$2`);
}

function swapReleaseSigningConfig(contents) {
  // Replace `signingConfig signingConfigs.debug` inside buildTypes.release with conditional version.
  // Target the FIRST occurrence inside buildTypes.release{} block.
  const releaseBuildTypeRegex = /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!releaseBuildTypeRegex.test(contents)) {
    // Already swapped or template changed.
    return contents;
  }
  return contents.replace(releaseBuildTypeRegex, `$1${RELEASE_SIGNING_CONFIG_USAGE.trim()}`);
}

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;
    contents = injectKeystoreLoader(contents);
    contents = injectReleaseSigningConfig(contents);
    contents = swapReleaseSigningConfig(contents);
    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = withReleaseSigning;